spring:
  security:
    oauth2:
      client:
        registration:
          gluu:
            client-id: <client-id>
            client-secret: <client-secret>
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
        provider:
          gluu:
            issuer-uri: <server-uri-root>
            user-name-attribute: name
