spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: test1
            client-secret: GAeGfBzxma4d3HQE7q5f68k3SZvXJqwO
            client-name: test1
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
        provider:
          keycloak:
            issuer-uri: http://10.94.184.167:8090/realms/qa
            user-name-attribute: name