spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: demo-app
            client-secret: jqgsBPZHP1AXaXs6dGMZPe91lMCBQxc5
            client-name: demo-sample-app
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
        provider:
          keycloak:
            issuer-uri: https://keycloak-scale.rakkau.com/realms/dev
            user-name-attribute: name